#!/bin/bash

cd "/home/dom/Dropbox/Xdrive/projects/Susruta project/Saktumiva2/saktumiva"
git pull
cd ..
git add saktumiva
git commit -m "saktumiva update"
#
cd "/home/dom/Dropbox/Xdrive/projects/Susruta project/Saktumiva2/lib"
git pull
cd ..
git add lib
git commit -m "lib update"


