#!/bin/bash -x

cd "/home/dom/Dropbox/Xdrive/projects/sushrutaproject1/Sushrutasamhita_Saktumiva2/saktumiva"
git pull
cd ..
git add saktumiva
git commit -m "saktumiva update"
#
cd "/home/dom/Dropbox/Xdrive/projects/sushrutaproject1/Sushrutasamhita_Saktumiva2/lib"
git pull
cd ..
git add lib
git commit -m "lib update"


